### ISSUE TITLE
Exclude hidden folders as well

### ISSUE THREAD

**Issue by scosman** [Kraymer/deus_ex_tmachina#1]
Thanks for making this!

I had hidden folders like `~/.dropbox` which were huge. 

Can I suggest you add this as well:
`ls -d ${HOME}/.*/  | tr '\n' '\n' | eval ${exclude_line} >> ${out}`

**Comment by Kraymer** [comment]
Aha crazy this small script is still useful to people!
I'll have a look at it, thanks

**Comment by scosman** [comment]
Thanks! And quite useful!

**Comment by Kraymer** [comment]
done by [3cc4c8e](https://github.com/Kraymer/deus_ex_tmachina/commit/3cc4c8ef446e6e51c0a5cc401f96044e2e10675e)
